"""
Alice's Grand Tournament (run_experiments.py)
---------------------------------------------
Automates the full comparison of:
1. Different Payloads (0.1, 0.5, 1.0 bpp) - The "Greediness"
2. Different Algorithms (LSB, PVD, DCT)
3. Different Models (RF, XGB, SVM)
"""
import os
import argparse
import subprocess
import pandas as pd # You might want pandas to save the results nicely

def main():
    # === Configuration Matrix ===
    # 1. Greediness Levels (Bits Per Pixel)
    payloads = [0.1, 0.4, 0.8] 
    
    # 2. Algorithms to compare
    algorithms = ["lsb", "pvd", "dct"] 
    
    # 3. Models to train
    models = ["rf", "xgb"] 
    
    cover_dir = ".../datasets" # Point this to your real images
    base_work_dir = ".../experiment_results"

    summary_results = []

    # === The Loop of Truth ===
    for bpp in payloads:
        print(f"\n✨ STARTING EXPERIMENT: Greediness (BPP) = {bpp} ✨")
        
        # Create a unique working directory for this payload
        # e.g. ./experiment_results/run_bpp_0.4
        work_dir = os.path.join(base_work_dir, f"run_bpp_{bpp}")
        
        # Construct the command line for your pipeline.py
        # We call it as a subprocess to keep memory clean between runs
        cmd = [
            "python", "-m", "stego_ai.pipeline",
            "--cover-dir", cover_dir,
            "--work-dir", work_dir,
            "--algorithms", *algorithms,
            "--models", *models,
            "--bpp", str(bpp),
            "--feature-method", "residual_hist", # Use our NEW feature method
            "--force-generate", # Force generation to ensure correct BPP
            "--force-prepare",
            "--save-models"
        ]
        
        print(f"Running spell: {' '.join(cmd)}")
        try:
            subprocess.run(cmd, check=True)
            
            # (Optional) Here you would parse the 'metrics.json' generated by pipeline.py
            # and append it to 'summary_results' so you can make a graph later.
            print(f"✅ Experiment BPP={bpp} completed successfully!")
            
        except subprocess.CalledProcessError as e:
            print(f"❌ Experiment BPP={bpp} failed! Error: {e}")

    print("\n🎉 All experiments finished! Klee would be proud of this explosion of data!")

if __name__ == "__main__":
    main()